# Change these first
owner: Yo-codeback # Your GitHub organization or username, where this repository lives
repo: bvc-status # The name of this repository

sites:
  - name: our_api 主要資料 (資料來源)
    url: https://bvc-api.deno.dev
    assignees: 
      - Yo-codeback
      - LukuMaker
  - name: moa_api 農業部資料 (副資料來源) 
    url: https://data.moa.gov.tw/Service/OpenData/FromM/FarmTransData.aspx
    assignees: 
      - moa
  - name: notify_api 通知頁面 (通知內容)
    url: https://bvcaanotify.deno.dev
    assignees: 
      - LukuMaker
          
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  baseUrl: /bvc-status # where "repo" is your repository name
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: "農產分析"
  introTitle: "農產分析 android 版本 現在正在實施封測!"
  introMessage: "此網站由 upptime 提供協助"
  navbar:
    - title: Status
      href: /bvc-status
    # - title: GitHub
      # href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

# Webhook 通知配置
notifications:
  webhook:
    # 使用 GitHub Secrets 中的 webhook URL（更安全）
    url: ${{ secrets.NOTIFICATION_DISCORD_WEBHOOK_URL }}
    # 支援的類型: slack, discord, custom
    type: discord
    # 是否在每次檢查後都發送通知（包括正常狀態）
    notify-on-check: false
    # 是否在狀態變化時發送通知
    notify-on-change: true
